@color_physical: lighten(#000, 85%); 
@color_physical_bright: #fff;
@color_water: lighten(#000, 85%);
@color_administrative_dark: lighten(#000, 55%);
@color_administrative_bright: #fff;
@color_administrative_medium_low: lighten(#000, 55%);
@color_administrative_medium_high: lighten(#000, 55%);
@color_administrative_medium_high2: lighten(#000, 55%);
@color_transport: lighten(#000, 55%);
@color_transport_casing: #fff;
@color_transport_inline: #fff;
@color_transport_tunnel: lighten(#ccc, 55%);
@color_transport_minor: #ccc;
@color_transport_rail: #afafaf;
@color_transport_path: #ededed;
@color_building_outline: lighten(#000, 85%);
@color_building_outline_special: lighten(#00aeef, 85%);
@color_airport_runways: #eee;
@color_airport_runways_detail: #f2f2f2;
@pattern_opacity: 0.15;

