# first export SHAPE_ENCODING=UTF-8

all:
	SHAPE_ENCODING=UTF-8 ogr2ogr -t_srs "EPSG:3857" -s_srs "EPSG:4326" merged_labels_z4.shp ../shp/city_labels/africa-labels-z4.shp
	SHAPE_ENCODING=UTF-8 ogr2ogr -t_srs "EPSG:3857" -s_srs "EPSG:4326" merged_labels_z4.shp -append ../shp/city_labels/asia-labels-z4.shp
	SHAPE_ENCODING=UTF-8 ogr2ogr -t_srs "EPSG:3857" -s_srs "EPSG:4326" merged_labels_z4.shp -append ../shp/city_labels/australia-new-zealand-labels-z4.shp
	SHAPE_ENCODING=UTF-8 ogr2ogr -t_srs "EPSG:3857" -s_srs "EPSG:4326" merged_labels_z4.shp -append ../shp/city_labels/europe-labels-z4.shp
	SHAPE_ENCODING=UTF-8 ogr2ogr -t_srs "EPSG:3857" -s_srs "EPSG:4326" merged_labels_z4.shp -append ../shp/city_labels/north-america-labels-z4.shp
	SHAPE_ENCODING=UTF-8 ogr2ogr -t_srs "EPSG:3857" -s_srs "EPSG:4326" merged_labels_z4.shp -append ../shp/city_labels/south-america-labels-z4.shp
	shapeindex merged_labels_z4.shp
	SHAPE_ENCODING=UTF-8 ogr2ogr -t_srs "EPSG:3857" -s_srs "EPSG:4326" merged_points_z4.shp ../shp/city_labels/africa-points-z4.shp
	SHAPE_ENCODING=UTF-8 ogr2ogr -t_srs "EPSG:3857" -s_srs "EPSG:4326" merged_points_z4.shp -append ../shp/city_labels/asia-points-z4.shp
	SHAPE_ENCODING=UTF-8 ogr2ogr -t_srs "EPSG:3857" -s_srs "EPSG:4326" merged_points_z4.shp -append ../shp/city_labels/australia-new-zealand-points-z4.shp
	SHAPE_ENCODING=UTF-8 ogr2ogr -t_srs "EPSG:3857" -s_srs "EPSG:4326" merged_points_z4.shp -append ../shp/city_labels/europe-points-z4.shp
	SHAPE_ENCODING=UTF-8 ogr2ogr -t_srs "EPSG:3857" -s_srs "EPSG:4326" merged_points_z4.shp -append ../shp/city_labels/north-america-points-z4.shp
	SHAPE_ENCODING=UTF-8 ogr2ogr -t_srs "EPSG:3857" -s_srs "EPSG:4326" merged_points_z4.shp -append ../shp/city_labels/south-america-points-z4.shp
	shapeindex merged_points_z4.shp
	SHAPE_ENCODING=UTF-8 ogr2ogr -t_srs "EPSG:3857" -s_srs "EPSG:4326" merged_labels_z5.shp ../shp/city_labels/africa-labels-z5.shp
	SHAPE_ENCODING=UTF-8 ogr2ogr -t_srs "EPSG:3857" -s_srs "EPSG:4326" merged_labels_z5.shp -append ../shp/city_labels/asia-labels-z5.shp
	SHAPE_ENCODING=UTF-8 ogr2ogr -t_srs "EPSG:3857" -s_srs "EPSG:4326" merged_labels_z5.shp -append ../shp/city_labels/australia-new-zealand-labels-z5.shp
	SHAPE_ENCODING=UTF-8 ogr2ogr -t_srs "EPSG:3857" -s_srs "EPSG:4326" merged_labels_z5.shp -append ../shp/city_labels/europe-labels-z5.shp
	SHAPE_ENCODING=UTF-8 ogr2ogr -t_srs "EPSG:3857" -s_srs "EPSG:4326" merged_labels_z5.shp -append ../shp/city_labels/north-america-labels-z5.shp
	SHAPE_ENCODING=UTF-8 ogr2ogr -t_srs "EPSG:3857" -s_srs "EPSG:4326" merged_labels_z5.shp -append ../shp/city_labels/south-america-labels-z5.shp
	shapeindex merged_labels_z5.shp
	SHAPE_ENCODING=UTF-8 ogr2ogr -t_srs "EPSG:3857" -s_srs "EPSG:4326" merged_points_z5.shp ../shp/city_labels/africa-points-z5.shp
	SHAPE_ENCODING=UTF-8 ogr2ogr -t_srs "EPSG:3857" -s_srs "EPSG:4326" merged_points_z5.shp -append ../shp/city_labels/asia-points-z5.shp
	SHAPE_ENCODING=UTF-8 ogr2ogr -t_srs "EPSG:3857" -s_srs "EPSG:4326" merged_points_z5.shp -append ../shp/city_labels/australia-new-zealand-points-z5.shp
	SHAPE_ENCODING=UTF-8 ogr2ogr -t_srs "EPSG:3857" -s_srs "EPSG:4326" merged_points_z5.shp -append ../shp/city_labels/europe-points-z5.shp
	SHAPE_ENCODING=UTF-8 ogr2ogr -t_srs "EPSG:3857" -s_srs "EPSG:4326" merged_points_z5.shp -append ../shp/city_labels/north-america-points-z5.shp
	SHAPE_ENCODING=UTF-8 ogr2ogr -t_srs "EPSG:3857" -s_srs "EPSG:4326" merged_points_z5.shp -append ../shp/city_labels/south-america-points-z5.shp
	shapeindex merged_points_z5.shp
	SHAPE_ENCODING=UTF-8 ogr2ogr -t_srs "EPSG:3857" -s_srs "EPSG:4326" merged_labels_z6.shp ../shp/city_labels/africa-labels-z6.shp
	SHAPE_ENCODING=UTF-8 ogr2ogr -t_srs "EPSG:3857" -s_srs "EPSG:4326" merged_labels_z6.shp -append ../shp/city_labels/asia-labels-z6.shp
	SHAPE_ENCODING=UTF-8 ogr2ogr -t_srs "EPSG:3857" -s_srs "EPSG:4326" merged_labels_z6.shp -append ../shp/city_labels/australia-new-zealand-labels-z6.shp
	SHAPE_ENCODING=UTF-8 ogr2ogr -t_srs "EPSG:3857" -s_srs "EPSG:4326" merged_labels_z6.shp -append ../shp/city_labels/europe-labels-z6.shp
	SHAPE_ENCODING=UTF-8 ogr2ogr -t_srs "EPSG:3857" -s_srs "EPSG:4326" merged_labels_z6.shp -append ../shp/city_labels/north-america-labels-z6.shp
	SHAPE_ENCODING=UTF-8 ogr2ogr -t_srs "EPSG:3857" -s_srs "EPSG:4326" merged_labels_z6.shp -append ../shp/city_labels/south-america-labels-z6.shp
	shapeindex merged_labels_z6.shp
	SHAPE_ENCODING=UTF-8 ogr2ogr -t_srs "EPSG:3857" -s_srs "EPSG:4326" merged_points_z6.shp ../shp/city_labels/africa-points-z6.shp
	SHAPE_ENCODING=UTF-8 ogr2ogr -t_srs "EPSG:3857" -s_srs "EPSG:4326" merged_points_z6.shp -append ../shp/city_labels/asia-points-z6.shp
	SHAPE_ENCODING=UTF-8 ogr2ogr -t_srs "EPSG:3857" -s_srs "EPSG:4326" merged_points_z6.shp -append ../shp/city_labels/australia-new-zealand-points-z6.shp
	SHAPE_ENCODING=UTF-8 ogr2ogr -t_srs "EPSG:3857" -s_srs "EPSG:4326" merged_points_z6.shp -append ../shp/city_labels/europe-points-z6.shp
	SHAPE_ENCODING=UTF-8 ogr2ogr -t_srs "EPSG:3857" -s_srs "EPSG:4326" merged_points_z6.shp -append ../shp/city_labels/north-america-points-z6.shp
	SHAPE_ENCODING=UTF-8 ogr2ogr -t_srs "EPSG:3857" -s_srs "EPSG:4326" merged_points_z6.shp -append ../shp/city_labels/south-america-points-z6.shp
	shapeindex merged_points_z6.shp
	SHAPE_ENCODING=UTF-8 ogr2ogr -t_srs "EPSG:3857" -s_srs "EPSG:4326" merged_labels_z7.shp ../shp/city_labels/africa-labels-z7.shp
	SHAPE_ENCODING=UTF-8 ogr2ogr -t_srs "EPSG:3857" -s_srs "EPSG:4326" merged_labels_z7.shp -append ../shp/city_labels/asia-labels-z7.shp
	SHAPE_ENCODING=UTF-8 ogr2ogr -t_srs "EPSG:3857" -s_srs "EPSG:4326" merged_labels_z7.shp -append ../shp/city_labels/australia-new-zealand-labels-z7.shp
	SHAPE_ENCODING=UTF-8 ogr2ogr -t_srs "EPSG:3857" -s_srs "EPSG:4326" merged_labels_z7.shp -append ../shp/city_labels/europe-labels-z7.shp
	SHAPE_ENCODING=UTF-8 ogr2ogr -t_srs "EPSG:3857" -s_srs "EPSG:4326" merged_labels_z7.shp -append ../shp/city_labels/north-america-labels-z7.shp
	SHAPE_ENCODING=UTF-8 ogr2ogr -t_srs "EPSG:3857" -s_srs "EPSG:4326" merged_labels_z7.shp -append ../shp/city_labels/south-america-labels-z7.shp
	shapeindex merged_labels_z7.shp
	SHAPE_ENCODING=UTF-8 ogr2ogr -t_srs "EPSG:3857" -s_srs "EPSG:4326" merged_points_z7.shp ../shp/city_labels/africa-points-z7.shp
	SHAPE_ENCODING=UTF-8 ogr2ogr -t_srs "EPSG:3857" -s_srs "EPSG:4326" merged_points_z7.shp -append ../shp/city_labels/asia-points-z7.shp
	SHAPE_ENCODING=UTF-8 ogr2ogr -t_srs "EPSG:3857" -s_srs "EPSG:4326" merged_points_z7.shp -append ../shp/city_labels/australia-new-zealand-points-z7.shp
	SHAPE_ENCODING=UTF-8 ogr2ogr -t_srs "EPSG:3857" -s_srs "EPSG:4326" merged_points_z7.shp -append ../shp/city_labels/europe-points-z7.shp
	SHAPE_ENCODING=UTF-8 ogr2ogr -t_srs "EPSG:3857" -s_srs "EPSG:4326" merged_points_z7.shp -append ../shp/city_labels/north-america-points-z7.shp
	SHAPE_ENCODING=UTF-8 ogr2ogr -t_srs "EPSG:3857" -s_srs "EPSG:4326" merged_points_z7.shp -append ../shp/city_labels/south-america-points-z7.shp
	shapeindex merged_points_z7.shp
	SHAPE_ENCODING=UTF-8 ogr2ogr -t_srs "EPSG:3857" -s_srs "EPSG:4326" merged_labels_z8.shp ../shp/city_labels/africa-labels-z8.shp
	SHAPE_ENCODING=UTF-8 ogr2ogr -t_srs "EPSG:3857" -s_srs "EPSG:4326" merged_labels_z8.shp -append ../shp/city_labels/asia-labels-z8.shp
	SHAPE_ENCODING=UTF-8 ogr2ogr -t_srs "EPSG:3857" -s_srs "EPSG:4326" merged_labels_z8.shp -append ../shp/city_labels/australia-new-zealand-labels-z8.shp
	SHAPE_ENCODING=UTF-8 ogr2ogr -t_srs "EPSG:3857" -s_srs "EPSG:4326" merged_labels_z8.shp -append ../shp/city_labels/europe-labels-z8.shp
	SHAPE_ENCODING=UTF-8 ogr2ogr -t_srs "EPSG:3857" -s_srs "EPSG:4326" merged_labels_z8.shp -append ../shp/city_labels/north-america-labels-z8.shp
	SHAPE_ENCODING=UTF-8 ogr2ogr -t_srs "EPSG:3857" -s_srs "EPSG:4326" merged_labels_z8.shp -append ../shp/city_labels/south-america-labels-z8.shp
	shapeindex merged_labels_z8.shp
	SHAPE_ENCODING=UTF-8 ogr2ogr -t_srs "EPSG:3857" -s_srs "EPSG:4326" merged_points_z8.shp ../shp/city_labels/africa-points-z8.shp
	SHAPE_ENCODING=UTF-8 ogr2ogr -t_srs "EPSG:3857" -s_srs "EPSG:4326" merged_points_z8.shp -append ../shp/city_labels/asia-points-z8.shp
	SHAPE_ENCODING=UTF-8 ogr2ogr -t_srs "EPSG:3857" -s_srs "EPSG:4326" merged_points_z8.shp -append ../shp/city_labels/australia-new-zealand-points-z8.shp
	SHAPE_ENCODING=UTF-8 ogr2ogr -t_srs "EPSG:3857" -s_srs "EPSG:4326" merged_points_z8.shp -append ../shp/city_labels/europe-points-z8.shp
	SHAPE_ENCODING=UTF-8 ogr2ogr -t_srs "EPSG:3857" -s_srs "EPSG:4326" merged_points_z8.shp -append ../shp/city_labels/north-america-points-z8.shp
	SHAPE_ENCODING=UTF-8 ogr2ogr -t_srs "EPSG:3857" -s_srs "EPSG:4326" merged_points_z8.shp -append ../shp/city_labels/south-america-points-z8.shp
	shapeindex merged_points_z8.shp
	SHAPE_ENCODING=UTF-8 ogr2ogr -t_srs "EPSG:3857" -s_srs "EPSG:4326" merged_points_z9.shp ../shp/city_labels/africa-points-z9.shp
	SHAPE_ENCODING=UTF-8 ogr2ogr -t_srs "EPSG:3857" -s_srs "EPSG:4326" merged_points_z9.shp -append ../shp/city_labels/asia-points-z9.shp
	SHAPE_ENCODING=UTF-8 ogr2ogr -t_srs "EPSG:3857" -s_srs "EPSG:4326" merged_points_z9.shp -append ../shp/city_labels/australia-new-zealand-points-z9.shp
	SHAPE_ENCODING=UTF-8 ogr2ogr -t_srs "EPSG:3857" -s_srs "EPSG:4326" merged_points_z9.shp -append ../shp/city_labels/europe-points-z9.shp
	SHAPE_ENCODING=UTF-8 ogr2ogr -t_srs "EPSG:3857" -s_srs "EPSG:4326" merged_points_z9.shp -append ../shp/city_labels/north-america-points-z9.shp
	SHAPE_ENCODING=UTF-8 ogr2ogr -t_srs "EPSG:3857" -s_srs "EPSG:4326" merged_points_z9.shp -append ../shp/city_labels/south-america-points-z9.shp
	shapeindex merged_points_z9.shp
	SHAPE_ENCODING=UTF-8 ogr2ogr -t_srs "EPSG:3857" -s_srs "EPSG:4326" merged_points_z10.shp ../shp/city_labels/africa-points-z10.shp
	SHAPE_ENCODING=UTF-8 ogr2ogr -t_srs "EPSG:3857" -s_srs "EPSG:4326" merged_points_z10.shp -append ../shp/city_labels/asia-points-z10.shp
	SHAPE_ENCODING=UTF-8 ogr2ogr -t_srs "EPSG:3857" -s_srs "EPSG:4326" merged_points_z10.shp -append ../shp/city_labels/australia-new-zealand-points-z10.shp
	SHAPE_ENCODING=UTF-8 ogr2ogr -t_srs "EPSG:3857" -s_srs "EPSG:4326" merged_points_z10.shp -append ../shp/city_labels/europe-points-z9.shp
	SHAPE_ENCODING=UTF-8 ogr2ogr -t_srs "EPSG:3857" -s_srs "EPSG:4326" merged_points_z10.shp -append ../shp/city_labels/north-america-points-z10.shp
	SHAPE_ENCODING=UTF-8 ogr2ogr -t_srs "EPSG:3857" -s_srs "EPSG:4326" merged_points_z10.shp -append ../shp/city_labels/south-america-points-z10.shp
	shapeindex merged_points_z10.shp

clean:
	rm merged*
